### PR TITLE
Added paper references

### LINKED ISSUE #128: Link to paper / Add CITATION.cff
# Feature
## Desired Behavior / Functionality
To make it easy for people to read more about paseos we should add a link to the paper to the readme and a [CITATION.rff](https://github.com/esa/torchquad/blob/main/CITATION.cff)

## What Needs to Be Done
see above

## How Can It Be Tested
look at readme :upside_down_face:

### PR DESCRIPTION
**Pull request by johanos1**
# Description

Summary of changes

* added CITATION.cff
* added reference in Readme.md

## Resolved Issues

- [ ] fixes #128 

## How Has This Been Tested?
Look at readme
## Related Pull Requests

- #PR

### CODE REVIEW

**Comment by johanos1** [comment]
No idea why the Citation.cff cannot be parsed?

**Comment by gomezzz** [comment]
> No idea why the Citation.cff cannot be parsed?

@johanos1 In line 12 I think you have an unexpected indent ;P

**Comment by johanos1** [comment]
Good eye! :)

**Review by gomezzz — APPROVED** [review]
:+1:

**Pull request merged**
